### PR TITLE
Support routing termination on client side

### PR DESCRIPTION
**Pull request by hero78119**
Server side support redirect by catch error in middleware

``` javascript
// extra/server.js
...
if (E) {
    if (E.redirect) {
        res.redirect(E.redirect);
        return;
    }
    console.log(E.stack || E);
}
```

To support redirect on client side, we can follow the similar `server.js` middleware logic to implement on client side `routeToUrl.js`.
With that, if we want redirect occur in `this.executeAction(this.routing)`. we can do 

``` javascript
// in a  routing action
... // do something 

// redirection occur here
...

// return `Promise.reject` to terminate original routing
var error = new Error('to redirect to error page');
error.hasHandled = true;
return Promise.reject(error);
```

to terminate `routeToUrl` and prevent real-go-to-url.
To generalize the situation, try to name as `hasHandled` instead of `redirect`

### CODE REVIEW

**Comment by zordius** [comment]
1. server side redirect is a special case , it break page rendering and wanna response different behavior , so we use promise.reject.
2. client side redirect is a generic case. If you wanna redirect to another URL, it means 'execute routeToUrl' again. It is a kind of success and we should still go Promise.resolve way.

**Comment by zordius** [comment]
more about 2:

review line 12 - 21 we will see:

```
update URL in store -> page action -> then -> emitChange for page re-rendering -> update history state
                                   -> catch -> error and go url
```

if you do something like this in your page action:

```
update another URL to store -> trigger another page action
```

Then it should be good. The better way to support this is to change line 21, url => this.getStore('page').getURL() .

**Comment by hero78119** [comment]
Yes, actually what I actually do is call `routeToUrl` again.
However, call `routeToUrl` in routing action again without returning `Promise.reject` on first will cause the first `routeToUrl` call override the redirect result because `Promise.resolve` won't terminate `window.history.pushState`

**Comment by hero78119** [comment]
I left comment-3 before see your comment-2.
comment-2 is a better solution!!
Let me think about it and verify again :)

**Comment by hero78119** [comment]
Try to fix regexp format error on commonStore for parsing port
[origin](https://regex101.com/r/tY1gQ2/2)
[after fixed](https://regex101.com/r/nW1iD0/2)

**Comment by zordius** [comment]
actually in your previous PR, the URL parsing logic is wrong (the protocol should not contain // , it is wrong. please dump location object from browser as standard reference) , I will rollback to original version.

**Comment by zordius** [comment]
after I review the regex101 it seems to be correct now.

**Pull request merged**
